// Rebuilds public/u1-implementation.js from the repo's own sources.
//
//   node sites/step-a11y/build.mjs
//
// The deployed file is DERIVED, never edited. Its library-corrections half is
// cut from ../../u1-patch.js — the single source for that code, the same file
// the panel inlines into every implementation guide it exports. A bug fixed
// there has to reach here, and a hand-made copy is how it silently would not:
// the landmarks wrapper was passing a bare object for roles whose schema
// demands an array, and the fix would have lived in the repo while the
// deployed site kept throwing "Invalid Landmarks props provided."
//
// Only the mappings are written by hand, in mappings.js.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');

// Only the regions these mappings need. Shipping listbox, datepicker and grid
// corrections to a site with none of them is dead code on every page load.
const REGIONS = ['core', 'form', 'tabs', 'menu', 'carousel', 'link', 'button'];

// The SAME region regex the panel's own exporter uses (getPatchSource in
// panel.js). Two different ways of slicing one file is two things to keep in
// step, and the whole point of this script is that there is one source.
const patchSrc = readFileSync(join(REPO, 'u1-patch.js'), 'utf8');
const re0 = /\/\/#region u1-patch:([a-z]+)\r?\n([\s\S]*?)\r?\n\/\/#endregion/g;
let patch = "'use strict';\n";
const found = new Set();
for (let m; (m = re0.exec(patchSrc)); ) {
  found.add(m[1]);
  if (REGIONS.includes(m[1])) patch += m[2] + '\n';
}
for (const r of REGIONS) {
  if (!found.has(r)) throw new Error(`u1-patch.js has no region "${r}" — it was renamed or removed`);
}

const mappings = readFileSync(join(HERE, 'mappings.js'), 'utf8');

// Section 5 is generated from the mappings it watches. The two lists must
// agree, and a hand-copied one is exactly how they drift.
const FIELD = {
  carousel: 'carouselContainer', menu: 'menu', tabs: 'tabList', form: 'form',
  link: 'element', button: 'element', heading: 'heading', accordion: 'headerSelector',
};
const checks = [];
const re = /\/\* ---- (m-[0-9a-f]+) — (\w+)\s+(.*?) ---- \*\/\s*\nwindow\.u1\?\.fix\.\w+\(/g;
for (let m; (m = re.exec(mappings)); ) {
  const [, id, type, root] = m;
  const field = FIELD[type];
  if (!field) throw new Error(`No monitored field known for component type "${type}"`);
  const body = mappings.slice(m.index, mappings.indexOf('});', re.lastIndex));
  const f = new RegExp(`${field}:\\s*("(?:[^"\\\\]|\\\\.)*")`).exec(body);
  checks.push({ id, type, field, selector: f ? JSON.parse(f[1]) : root.trim(), page: '/' });
}

const out = `/* ============================================================
 * U1 accessibility implementation — step-shoe-store (accessible copy)
 * GENERATED by sites/step-a11y/build.mjs — do not edit by hand.
 * Corrections come from u1-patch.js; mappings from mappings.js.
 * Load AFTER u1_vanilla-js-a11y.js.
 * ============================================================ */

/* ---- 0. Configuration ---- */
window.u1?.setConfiguration({
  visualFocus: { style: { color: "#762323", doubleBorder: true, secondaryColor: "#000000" } }
});

/* ---- 1. Library corrections ---- */
${patch}
${mappings}
/* ---- 5. Monitoring hook (only runs with ?u1qa=1) ---- */
(function () {
  try {
    if (new URLSearchParams(location.search).get('u1qa') !== '1') return;
    var CHECKS = ${JSON.stringify(checks)};
    var here = (location.pathname || '/').replace(/\\/+$/, '') || '/';
    function run() {
      CHECKS.forEach(function (c) {
        try {
          if (c.page && c.page !== here) return;
          var ok = false; try { ok = !!document.querySelector(c.selector); } catch (e) { ok = false; }
          if (!ok) console.error('U1-VALIDATION-ERROR | domain=' + location.hostname + ' | type=' + c.type +
            ' | id=' + c.id + ' | field=' + c.field + ' | selector=' + c.selector + ' | page=' + location.pathname);
        } catch (e) {}
      });
    }
    if (document.readyState === 'complete') setTimeout(run, 800);
    else window.addEventListener('load', function () { setTimeout(run, 800); });
  } catch (e) {}
})();
`;

writeFileSync(join(HERE, 'public', 'u1-implementation.js'), out);
console.log(`Built public/u1-implementation.js — ${out.length} bytes, ` +
            `${REGIONS.length} patch regions, ${checks.length} mappings monitored.`);
